//! LightVC VST3 Plugin
//!
//! Real-time voice conversion as a VST3 audio effect.
//! Uses nice-plug + nice-plug-egui.

use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};
use std::time::Instant;

use crossbeam_channel::{unbounded, Receiver, Sender};
use nice_plug::prelude::*;
use nice_plug_egui::{create_egui_editor, EguiState};

// ---------------------------------------------------------------------------
// Parameters
// ---------------------------------------------------------------------------

#[derive(Params)]
struct LightVcParams {
    #[id = "bypass"]
    pub bypass: BoolParam,

    #[id = "mode"]
    pub mode: IntParam,

    #[id = "mix"]
    pub mix: FloatParam,

    #[id = "gain"]
    pub output_gain: FloatParam,

    #[persist = "model-path"]
    pub model_path: Arc<Mutex<String>>,

    #[persist = "dac-path"]
    pub dac_path: Arc<Mutex<String>>,

    /// Optional explicit converter config JSON path. If empty, the plugin
    /// looks for `{model_basename}_config.json` next to the model file
    /// (generated by `training/export_weights.py`). Falls back to
    /// `ConverterConfig::default()` if neither exists.
    #[persist = "config-path"]
    pub config_path: Arc<Mutex<String>>,

    #[persist = "editor-state"]
    pub editor_state: Arc<EguiState>,
}

impl Default for LightVcParams {
    fn default() -> Self {
        Self {
            bypass: BoolParam::new("Bypass", false),
            mode: IntParam::new("Mode", 1, IntRange::Linear { min: 0, max: 2 }),
            mix: FloatParam::new(
                "Mix",
                100.0,
                FloatRange::Linear {
                    min: 0.0,
                    max: 100.0,
                },
            )
            .with_smoother(SmoothingStyle::Linear(50.0))
            .with_unit("%"),
            output_gain: FloatParam::new(
                "Output",
                0.0,
                FloatRange::Skewed {
                    min: -24.0,
                    max: 24.0,
                    factor: FloatRange::gain_skew_factor(-24.0, 24.0),
                },
            )
            .with_smoother(SmoothingStyle::Logarithmic(20.0))
            .with_unit(" dB"),
            model_path: Arc::new(Mutex::new(String::new())),
            dac_path: Arc::new(Mutex::new(String::new())),
            config_path: Arc::new(Mutex::new(String::new())),
            editor_state: EguiState::from_size(400, 300),
        }
    }
}

// ---------------------------------------------------------------------------
// Communication
// ---------------------------------------------------------------------------

#[derive(Clone, Debug, Default)]
struct Metrics {
    input_rms: f32,
    output_rms: f32,
    rtf: f32,
    pipeline_ready: bool,
    /// Algorithmic + buffer latency estimate in ms ([06-8]).
    latency_ms: f32,
    /// "default" | "explicit" | "sidecar" — how the converter config was loaded.
    config_source: String,
    /// Human-readable summary of the active converter config.
    config_summary: String,
}

enum Task {
    LoadModels {
        dac_path: String,
        converter_path: String,
        config_path: String,
    },
    SetRingBuffers {
        capture_rx: rtrb::Consumer<f32>,
        playback_tx: rtrb::Producer<f32>,
    },
    /// Switch latency/quality mode ([06-6]). 0=Strict, 1=Balanced, 2=Quality.
    SetMode(u8),
    /// Set host sample rate for resampling ([06-5]).
    SetSampleRate(u32),
}

// ---------------------------------------------------------------------------
// Plugin
// ---------------------------------------------------------------------------

struct LightVcPlugin {
    params: Arc<LightVcParams>,
    task_tx: Sender<Task>,
    metrics_rx: Receiver<Metrics>,
    pipeline_ready: Arc<AtomicBool>,
    metrics: Arc<Mutex<Metrics>>,
    // Ring buffer handles for process() (host audio thread)
    capture_tx: Option<rtrb::Producer<f32>>,
    playback_rx: Option<rtrb::Consumer<f32>>,
    // Latency in samples (reported to host)
    latency_samples: u32,
    /// Last mode value sent to inference thread ([06-6]).
    last_mode: u8,
}

impl Default for LightVcPlugin {
    fn default() -> Self {
        let (task_tx, task_rx) = unbounded();
        let (metrics_tx, metrics_rx) = unbounded();
        let pipeline_ready = Arc::new(AtomicBool::new(false));
        let metrics = Arc::new(Mutex::new(Metrics::default()));

        let pr = pipeline_ready.clone();
        let mt = metrics.clone();

        std::thread::spawn(move || {
            inference_thread(task_rx, metrics_tx, pr, mt);
        });

        Self {
            params: Arc::new(LightVcParams::default()),
            task_tx,
            metrics_rx,
            pipeline_ready,
            metrics,
            capture_tx: None,
            playback_rx: None,
            latency_samples: 0,
            last_mode: 1, // Balanced
        }
    }
}

impl Plugin for LightVcPlugin {
    const NAME: &'static str = "LightVC";
    const VENDOR: &'static str = "LightVC";
    const URL: &'static str = "https://github.com/kjranyone/LightVC";
    const EMAIL: &'static str = "";
    const VERSION: &'static str = "0.1.0";

    const AUDIO_IO_LAYOUTS: &'static [AudioIOLayout] = &[AudioIOLayout {
        main_input_channels: NonZeroU32::new(1),
        main_output_channels: NonZeroU32::new(1),
        aux_input_ports: &[],
        aux_output_ports: &[],
        names: PortNames {
            layout: Some("LightVC Mono"),
            main_input: Some("Input"),
            main_output: Some("Output"),
            aux_inputs: &[],
            aux_outputs: &[],
        },
    }];

    const SAMPLE_ACCURATE_AUTOMATION: bool = true;
    type SysExMessage = ();
    type BackgroundTask = Task;

    fn params(&self) -> Arc<dyn Params> {
        self.params.clone()
    }

    fn editor(&mut self, _async_executor: AsyncExecutor<Self>) -> Option<Box<dyn Editor>> {
        let params = self.params.clone();
        let metrics = self.metrics.clone();
        let ready = self.pipeline_ready.load(Ordering::Relaxed);
        let task_tx = self.task_tx.clone();

        struct EditorUserState {
            metrics: Arc<Mutex<Metrics>>,
            params: Arc<LightVcParams>,
            ready: bool,
            task_tx: Sender<Task>,
        }

        // Kawaii color constants for the plugin editor
        const BG: egui::Color32 = egui::Color32::from_rgb(28, 22, 38);
        const PANEL: egui::Color32 = egui::Color32::from_rgb(42, 32, 56);
        const PINK: egui::Color32 = egui::Color32::from_rgb(255, 130, 190);
        const PINK_BRIGHT: egui::Color32 = egui::Color32::from_rgb(255, 160, 210);
        const LAVENDER: egui::Color32 = egui::Color32::from_rgb(170, 140, 255);
        const CYAN: egui::Color32 = egui::Color32::from_rgb(120, 230, 255);
        const MINT: egui::Color32 = egui::Color32::from_rgb(130, 255, 200);
        const YELLOW: egui::Color32 = egui::Color32::from_rgb(255, 220, 130);
        const TEXT: egui::Color32 = egui::Color32::from_rgb(240, 235, 250);
        const TEXT_DIM: egui::Color32 = egui::Color32::from_rgb(160, 150, 180);

        create_egui_editor(
            self.params.editor_state.clone(),
            EditorUserState {
                metrics,
                params,
                ready,
                task_tx,
            },
            nice_plug_egui::EguiSettings::default(),
            |ctx, _queue, _state| {
                // Apply dark kawaii background
                let mut style = (*ctx.global_style()).clone();
                style.visuals.dark_mode = true;
                style.visuals.panel_fill = BG;
                style.visuals.widgets.inactive.bg_fill = PANEL;
                style.visuals.widgets.hovered.bg_fill = PINK;
                style.visuals.widgets.active.bg_fill = LAVENDER;
                style.spacing.item_spacing = egui::vec2(8.0, 6.0);
                ctx.set_global_style(style);
            },
            move |ui, setter, _queue, state| {
                let m = state.metrics.lock().unwrap().clone();
                let params = state.params.clone();

                // Header
                ui.horizontal(|ui| {
                    ui.label(
                        egui::RichText::new("✦ LightVC")
                            .size(16.0)
                            .strong()
                            .color(PINK_BRIGHT),
                    );
                });

                ui.add_space(6.0);

                // Status
                let (dot_color, status_text) = if state.ready {
                    (MINT, "● READY")
                } else {
                    (TEXT_DIM, "● NO MODEL")
                };
                ui.label(egui::RichText::new(status_text).size(13.0).color(dot_color));

                ui.add_space(8.0);

                // Metrics
                if state.ready {
                    // Converter config summary (source + variant)
                    if !m.config_summary.is_empty() {
                        ui.horizontal(|ui| {
                            ui.label(egui::RichText::new("CFG").size(10.0).color(TEXT_DIM));
                            let color = match m.config_source.as_str() {
                                "explicit" => MINT,
                                "sidecar" => CYAN,
                                _ => YELLOW,
                            };
                            ui.label(
                                egui::RichText::new(format!(
                                    "[{}] {}",
                                    m.config_source, m.config_summary
                                ))
                                .size(10.0)
                                .color(color),
                            );
                        });
                    }

                    // Level bars
                    ui.horizontal(|ui| {
                        ui.label(egui::RichText::new("In").size(11.0).color(TEXT_DIM));
                        let (rect, _) =
                            ui.allocate_exact_size(egui::vec2(80.0, 10.0), egui::Sense::hover());
                        let level = (m.input_rms * 10.0).min(1.0).max(0.0);
                        ui.painter().rect_filled(rect, 4.0, BG);
                        ui.painter().rect_filled(
                            egui::Rect::from_min_size(
                                rect.min,
                                egui::vec2(rect.width() * level, rect.height()),
                            ),
                            4.0,
                            if level > 0.8 {
                                PINK
                            } else if level > 0.5 {
                                YELLOW
                            } else {
                                MINT
                            },
                        );
                    });
                    ui.horizontal(|ui| {
                        ui.label(egui::RichText::new("Out").size(11.0).color(TEXT_DIM));
                        let (rect, _) =
                            ui.allocate_exact_size(egui::vec2(80.0, 10.0), egui::Sense::hover());
                        let level = (m.output_rms * 10.0).min(1.0).max(0.0);
                        ui.painter().rect_filled(rect, 4.0, BG);
                        ui.painter().rect_filled(
                            egui::Rect::from_min_size(
                                rect.min,
                                egui::vec2(rect.width() * level, rect.height()),
                            ),
                            4.0,
                            if level > 0.8 {
                                PINK
                            } else if level > 0.5 {
                                YELLOW
                            } else {
                                CYAN
                            },
                        );
                    });
                    ui.label(
                        egui::RichText::new(format!("RTF: {:.2}", m.rtf))
                            .size(10.0)
                            .color(TEXT_DIM),
                    );
                    ui.label(
                        egui::RichText::new(format!("Latency: {:.0} ms", m.latency_ms))
                            .size(10.0)
                            .color(TEXT_DIM),
                    );
                }

                ui.add_space(10.0);

                // Bypass button
                let bypassed = params.bypass.value();
                let btn_text = if bypassed { "▶ ENGAGE" } else { "■ BYPASS" };
                let btn = egui::Button::new(
                    egui::RichText::new(btn_text)
                        .size(13.0)
                        .strong()
                        .color(TEXT),
                )
                .fill(if bypassed { LAVENDER } else { PINK })
                .stroke(egui::Stroke::new(2.0, CYAN))
                .min_size(egui::vec2(120.0, 30.0));
                if ui.add(btn).clicked() {
                    setter.set_parameter(&params.bypass, !bypassed);
                }

                ui.add_space(6.0);

                // Mode buttons
                ui.label(egui::RichText::new("Mode").size(11.0).color(TEXT_DIM));
                ui.horizontal(|ui| {
                    let mode_val = params.mode.value();
                    for (val, name) in [(0, "Strict"), (1, "Balanced"), (2, "Quality")] {
                        let selected = mode_val == val;
                        let btn = egui::Button::new(
                            egui::RichText::new(name).size(11.0).color(if selected {
                                TEXT
                            } else {
                                TEXT_DIM
                            }),
                        )
                        .fill(if selected { PINK } else { PANEL })
                        .stroke(egui::Stroke::new(
                            1.0,
                            if selected { PINK_BRIGHT } else { LAVENDER },
                        ));
                        if ui.add(btn).clicked() {
                            setter.set_parameter(&params.mode, val);
                        }
                    }
                });

                ui.add_space(8.0);

                // Mix + Gain knobs (pure egui, no image assets)
                ui.horizontal(|ui| {
                    // Mix knob
                    let mix_val = params.mix.value();
                    let mix_norm = mix_val / 100.0;
                    if let Some(new) =
                        egui_knob(ui, "mix_knob", mix_norm, "Mix", &format!("{:.0}%", mix_val))
                    {
                        setter.set_parameter(&params.mix, new * 100.0);
                    }

                    ui.add_space(12.0);

                    // Gain knob
                    let gain_val = params.output_gain.value();
                    let gain_norm = (gain_val + 24.0) / 48.0;
                    if let Some(new) = egui_knob(
                        ui,
                        "gain_knob",
                        gain_norm,
                        "Gain",
                        &format!("{:+.1}dB", gain_val),
                    ) {
                        setter.set_parameter(&params.output_gain, new * 48.0 - 24.0);
                    }
                });

                ui.add_space(8.0);

                // ---- Model paths ([06-7]) ----
                ui.collapsing("Model Paths", |ui| {
                    let mut model = params.model_path.lock().unwrap().clone();
                    let mut dac = params.dac_path.lock().unwrap().clone();
                    let mut config = params.config_path.lock().unwrap().clone();

                    ui.label(
                        egui::RichText::new("Converter (.safetensors)")
                            .size(9.0)
                            .color(TEXT_DIM),
                    );
                    ui.add(
                        egui::TextEdit::singleline(&mut model)
                            .desired_width(360.0)
                            .text_color(TEXT),
                    );
                    ui.label(
                        egui::RichText::new("DAC (.safetensors)")
                            .size(9.0)
                            .color(TEXT_DIM),
                    );
                    ui.add(
                        egui::TextEdit::singleline(&mut dac)
                            .desired_width(360.0)
                            .text_color(TEXT),
                    );
                    ui.label(
                        egui::RichText::new("Config JSON (optional — auto-detected if empty)")
                            .size(9.0)
                            .color(TEXT_DIM),
                    );
                    ui.add(
                        egui::TextEdit::singleline(&mut config)
                            .desired_width(360.0)
                            .text_color(TEXT),
                    );

                    if ui.button("Load Models").clicked() {
                        *params.model_path.lock().unwrap() = model.clone();
                        *params.dac_path.lock().unwrap() = dac.clone();
                        *params.config_path.lock().unwrap() = config.clone();
                        if !model.is_empty() && !dac.is_empty() {
                            let _ = state.task_tx.send(Task::LoadModels {
                                dac_path: dac,
                                converter_path: model,
                                config_path: config,
                            });
                        }
                    }
                });
            },
        )
    }

    fn initialize(
        &mut self,
        _audio_io_layout: &AudioIOLayout,
        buffer_config: &BufferConfig,
        context: &mut impl InitContext<Self>,
    ) -> bool {
        let sr = buffer_config.sample_rate;
        let cap = (sr as usize / 5).max(16384);
        let (capture_tx, capture_rx) = rtrb::RingBuffer::new(cap);
        let (playback_tx, playback_rx) = rtrb::RingBuffer::new(cap);

        // Keep write/playback ends in plugin for process()
        self.capture_tx = Some(capture_tx);
        self.playback_rx = Some(playback_rx);

        // Send read/playback-write ends to inference thread
        let _ = self.task_tx.send(Task::SetRingBuffers {
            capture_rx,
            playback_tx,
        });
        // Inform inference thread of host sample rate for resampling ([06-5]).
        let _ = self.task_tx.send(Task::SetSampleRate(sr as u32));

        // Report initial latency (balanced mode: ~4 chunks at 44100Hz)
        // chunk = 4 * 512 = 2048 samples at 44100Hz
        // Rescaled to host sample rate
        let chunk_44k = 2048.0_f32;
        let latency_44k = chunk_44k * 3.0; // 3 chunks of buffer + processing
        self.latency_samples = (latency_44k * sr / 44100.0) as u32;
        context.set_latency_samples(self.latency_samples);

        let model = self.params.model_path.lock().unwrap().clone();
        let dac = self.params.dac_path.lock().unwrap().clone();
        let config = self.params.config_path.lock().unwrap().clone();
        if !model.is_empty() && !dac.is_empty() {
            let _ = self.task_tx.send(Task::LoadModels {
                dac_path: dac,
                converter_path: model,
                config_path: config,
            });
        }

        true
    }

    fn process(
        &mut self,
        buffer: &mut Buffer,
        _aux: &mut AuxiliaryBuffers,
        _context: &mut impl ProcessContext<Self>,
    ) -> ProcessStatus {
        // Update metrics
        {
            let mut m = self.metrics.lock().unwrap();
            while let Ok(r) = self.metrics_rx.try_recv() {
                *m = r;
            }
        }

        let bypass = self.params.bypass.value();
        let mix = self.params.mix.smoothed.next() / 100.0;
        let gain_db = self.params.output_gain.smoothed.next();
        let gain_linear = 10.0f32.powf(gain_db / 20.0);

        // Propagate mode changes to the inference thread ([06-6]).
        let mode_val = self.params.mode.value() as u8;
        if mode_val != self.last_mode {
            self.last_mode = mode_val;
            let _ = self.task_tx.send(Task::SetMode(mode_val));
        }

        if bypass || !self.pipeline_ready.load(Ordering::Relaxed) {
            // Bypass: dry pass-through with gain
            for channel_samples in buffer.iter_samples() {
                for sample in channel_samples {
                    *sample *= gain_linear;
                }
            }
            return ProcessStatus::Normal;
        }

        let (Some(tx), Some(rx)) = (self.capture_tx.as_mut(), self.playback_rx.as_mut()) else {
            return ProcessStatus::Normal;
        };

        // Push input samples to capture ring buffer, pop from playback ring buffer
        for channel_samples in buffer.iter_samples() {
            for sample in channel_samples {
                let input = *sample;
                let _ = tx.push(input);
                let processed = rx.pop().unwrap_or(0.0);
                // Dry/wet mix + output gain
                *sample = (input * (1.0 - mix) + processed * mix) * gain_linear;
            }
        }

        ProcessStatus::Normal
    }
}

// ---------------------------------------------------------------------------
// Resampler (host SR ↔ 44.1 kHz)  [06-5]
// ---------------------------------------------------------------------------

use rubato::{
    audioadapter_buffers::direct::SequentialSlice, Async, FixedAsync, Resampler as _,
    SincInterpolationParameters, SincInterpolationType, WindowFunction,
};

struct ClapResampler {
    up: Async<f32>,
    down: Async<f32>,
    up_out: Vec<f32>,
    down_out: Vec<f32>,
}

impl ClapResampler {
    fn new(host_sr: usize, chunk_size: usize) -> anyhow::Result<Self> {
        let params = SincInterpolationParameters {
            sinc_len: 256,
            f_cutoff: 0.95,
            interpolation: SincInterpolationType::Linear,
            oversampling_factor: 256,
            window: WindowFunction::BlackmanHarris2,
        };
        let ratio_up = 44_100.0 / host_sr as f64;
        let ratio_down = host_sr as f64 / 44_100.0;
        let up = Async::<f32>::new_sinc(ratio_up, 2.0, &params, chunk_size, 1, FixedAsync::Input)?;
        let down_chunk = (chunk_size as f64 * ratio_down).round().max(1.0) as usize;
        let down =
            Async::<f32>::new_sinc(ratio_down, 2.0, &params, down_chunk, 1, FixedAsync::Output)?;
        Ok(Self {
            up_out: vec![0.0; up.output_frames_max()],
            down_out: vec![0.0; down.output_frames_max()],
            up,
            down,
        })
    }

    fn process_up(&mut self, input: &[f32]) -> anyhow::Result<&[f32]> {
        let needed = self.up.input_frames_next();
        if input.len() < needed {
            return Err(anyhow::anyhow!(
                "process_up: need {needed}, got {}",
                input.len()
            ));
        }
        let frames_out = self.up.output_frames_next();
        let in_adapter = SequentialSlice::new(input, 1, needed)?;
        let mut out_adapter = SequentialSlice::new_mut(&mut self.up_out, 1, frames_out)?;
        let (_used, written) = self
            .up
            .process_into_buffer(&in_adapter, &mut out_adapter, None)?;
        Ok(&self.up_out[..written])
    }

    fn process_down(&mut self, input: &[f32]) -> anyhow::Result<&[f32]> {
        let needed = self.down.input_frames_next();
        if input.len() < needed {
            return Err(anyhow::anyhow!(
                "process_down: need {needed}, got {}",
                input.len()
            ));
        }
        let frames_out = self.down.output_frames_next();
        let in_adapter = SequentialSlice::new(input, 1, needed)?;
        let mut out_adapter = SequentialSlice::new_mut(&mut self.down_out, 1, frames_out)?;
        let (_used, written) =
            self.down
                .process_into_buffer(&in_adapter, &mut out_adapter, None)?;
        Ok(&self.down_out[..written])
    }

    fn input_frames_needed_up(&self) -> usize {
        self.up.input_frames_next()
    }

    fn input_frames_needed_down(&self) -> usize {
        self.down.input_frames_next()
    }
}

// ---------------------------------------------------------------------------
// Inference thread
// ---------------------------------------------------------------------------

fn inference_thread(
    task_rx: Receiver<Task>,
    metrics_tx: Sender<Metrics>,
    pipeline_ready: Arc<AtomicBool>,
    metrics: Arc<Mutex<Metrics>>,
) {
    let mut pipeline: Option<Arc<Mutex<lightvc_core::pipeline::VcPipeline>>> = None;
    let mut capture_rx: Option<rtrb::Consumer<f32>> = None;
    let mut playback_tx: Option<rtrb::Producer<f32>> = None;

    // Resampling state ([06-5]). Currently unused — reserved for the
    // future host-sample-rate resampling path.
    #[allow(unused_variables, unused_assignments)]
    let mut host_sr: u32 = 44_100;
    let mut resampler: Option<ClapResampler> = None;

    // 3-stage accumulation buffers ([06-5], mirroring realtime_tab.rs [05-4]).
    let mut in_accum: Vec<f32> = Vec::new(); // host-SR samples from capture ring
    let mut pcm_44k_accum: Vec<f32> = Vec::new(); // 44.1k samples ready for VC
    let mut out_44k_accum: Vec<f32> = Vec::new(); // 44.1k VC output
    let mut out_host_accum: Vec<f32> = Vec::new(); // host-SR output ready for playback

    loop {
        while let Ok(task) = task_rx.try_recv() {
            match task {
                Task::SetRingBuffers {
                    capture_rx: crx,
                    playback_tx: ptx,
                } => {
                    capture_rx = Some(crx);
                    playback_tx = Some(ptx);
                }
                Task::LoadModels {
                    dac_path,
                    converter_path,
                    config_path,
                } => match load_pipeline(&dac_path, &converter_path, &config_path) {
                    Ok((p, info)) => {
                        pipeline = Some(Arc::new(Mutex::new(p)));
                        pipeline_ready.store(true, Ordering::Relaxed);
                        let mut m = metrics.lock().unwrap();
                        m.pipeline_ready = true;
                        m.config_source = info.source;
                        m.config_summary = info.summary;
                        drop(m);
                    }
                    Err(e) => {
                        nice_log!("Model load failed: {e}");
                        pipeline_ready.store(false, Ordering::Relaxed);
                    }
                },
                Task::SetMode(val) => {
                    if let Some(p) = &pipeline {
                        let mode = match val {
                            0 => lightvc_core::converter::LatencyMode::Strict,
                            2 => lightvc_core::converter::LatencyMode::Quality,
                            _ => lightvc_core::converter::LatencyMode::Balanced,
                        };
                        if let Ok(mut pl) = p.lock() {
                            pl.set_mode(mode);
                            // Mode change resets streaming state; clear buffers.
                            in_accum.clear();
                            pcm_44k_accum.clear();
                            out_44k_accum.clear();
                            out_host_accum.clear();
                            nice_log!("Mode switched: {mode:?}");
                        }
                    }
                }
                Task::SetSampleRate(sr) => {
                    #[allow(unused_assignments)]
                    {
                        host_sr = sr;
                    }
                    if sr != 44_100 {
                        match ClapResampler::new(sr as usize, 2048) {
                            Ok(r) => {
                                resampler = Some(r);
                                nice_log!("Resampler active: {sr} Hz ↔ 44100 Hz");
                            }
                            Err(e) => {
                                nice_log!("Resampler init failed ({e}), assuming 44100 Hz");
                                resampler = None;
                            }
                        }
                    } else {
                        resampler = None;
                        nice_log!("Host SR = 44100 Hz, no resampling needed");
                    }
                    // Clear all buffers on SR change.
                    in_accum.clear();
                    pcm_44k_accum.clear();
                    out_44k_accum.clear();
                    out_host_accum.clear();
                }
            }
        }

        let (Some(p), Some(crx), Some(ptx)) = (&pipeline, &mut capture_rx, &mut playback_tx) else {
            std::thread::sleep(std::time::Duration::from_millis(50));
            continue;
        };

        let chunk_sz = p.lock().map(|pl| pl.chunk_samples()).unwrap_or(2048);

        // ---- Stage 1: drain capture ring into in_accum ----
        while let Ok(s) = crx.pop() {
            in_accum.push(s);
        }

        // ---- Stage 2: resample host-SR → 44.1k (or bypass) ----
        if let Some(rsm) = &mut resampler {
            let needed_up = rsm.input_frames_needed_up();
            while in_accum.len() >= needed_up {
                let (chunk, rest) = in_accum.split_at(needed_up);
                match rsm.process_up(chunk) {
                    Ok(out44) => pcm_44k_accum.extend_from_slice(out44),
                    Err(e) => nice_log!("process_up: {e}"),
                }
                in_accum = rest.to_vec();
            }
        } else {
            // No resampling: move directly.
            pcm_44k_accum.append(&mut in_accum);
        }

        // ---- Stage 3: process VC chunks at 44.1k ----
        let mut did_process = false;
        let mut in_rms = 0.0f32;
        let mut process_elapsed = std::time::Duration::ZERO;
        let mut out_samples_total = 0usize;

        while pcm_44k_accum.len() >= chunk_sz {
            let (chunk, rest) = pcm_44k_accum.split_at(chunk_sz);
            let chunk_owned = chunk.to_vec();
            pcm_44k_accum = rest.to_vec();

            in_rms = rms(&chunk_owned);
            let t0 = Instant::now();
            let out = match p.lock() {
                Ok(mut pl) => pl.process_chunk(&chunk_owned).unwrap_or_else(|e| {
                    nice_log!("VC: {e}");
                    chunk_owned.clone()
                }),
                Err(_) => break,
            };
            process_elapsed += t0.elapsed();
            out_samples_total += out.len();
            out_44k_accum.extend_from_slice(&out);
            did_process = true;
        }

        // ---- Stage 4: resample 44.1k → host-SR (or bypass) → playback ----
        if let Some(rsm) = &mut resampler {
            let needed_down = rsm.input_frames_needed_down();
            while out_44k_accum.len() >= needed_down {
                let (chunk, rest) = out_44k_accum.split_at(needed_down);
                match rsm.process_down(chunk) {
                    Ok(out_host) => {
                        for &s in out_host {
                            let _ = ptx.push(s);
                        }
                    }
                    Err(e) => nice_log!("process_down: {e}"),
                }
                out_44k_accum = rest.to_vec();
            }
        } else {
            for &s in &out_44k_accum {
                let _ = ptx.push(s);
            }
            out_44k_accum.clear();
        }

        // ---- Metrics ----
        if did_process {
            let out_rms_val = if out_samples_total > 0 {
                // Approximate: use last chunk's output via the accumulator tail.
                let tail_start = out_host_accum.len().saturating_sub(out_samples_total);
                rms(&out_host_accum[tail_start.min(out_host_accum.len())..])
            } else {
                0.0
            };
            let audio_dur_s = out_samples_total as f32 / 44_100.0;
            let rtf = if audio_dur_s > 0.0 {
                process_elapsed.as_secs_f32() / audio_dur_s
            } else {
                0.0
            };
            // Latency estimate: algorithmic + cpal buffers + resample ([06-8]).
            let algo_ms = p
                .lock()
                .map(|pl| pl.algorithmic_latency_ms())
                .unwrap_or(0.0);
            let latency_ms = 10.0 + 3.0 + algo_ms + 3.0 + 10.0;
            let (cfg_src, cfg_sum) = {
                let m = metrics.lock().unwrap();
                (m.config_source.clone(), m.config_summary.clone())
            };
            let _ = metrics_tx.send(Metrics {
                input_rms: in_rms,
                output_rms: out_rms_val,
                rtf,
                pipeline_ready: true,
                latency_ms,
                config_source: cfg_src,
                config_summary: cfg_sum,
            });
        }

        if !did_process {
            std::thread::sleep(std::time::Duration::from_millis(2));
        }
    }
}

fn rms(samples: &[f32]) -> f32 {
    if samples.is_empty() {
        return 0.0;
    }
    let sum_sq: f32 = samples.iter().map(|s| s * s).sum();
    (sum_sq / samples.len() as f32).sqrt()
}

/// Resolved converter configuration + provenance, for UI feedback.
struct ConverterConfigInfo {
    /// "explicit" | "sidecar" | "default"
    source: String,
    /// Short human-readable summary, e.g. "flow, hidden=256, timbre=off".
    summary: String,
}

/// Load converter config from, in order:
///   1. explicit `config_path` JSON (if set and readable)
///   2. `{converter_path without extension}_config.json` sidecar (written by
///      `training/export_weights.py`)
///   3. `ConverterConfig::default()` (legacy single-variant fallback)
fn load_converter_config(
    converter_path: &str,
    config_path: &str,
) -> (lightvc_core::ConverterConfig, ConverterConfigInfo) {
    let try_read_json = |p: &str| -> Option<lightvc_core::ConverterConfig> {
        let text = std::fs::read_to_string(p).ok()?;
        serde_json::from_str(&text).ok()
    };

    // 1. explicit config path
    if !config_path.is_empty() {
        if let Some(cfg) = try_read_json(config_path) {
            let summary = summarize_config(&cfg);
            return (
                cfg,
                ConverterConfigInfo {
                    source: "explicit".into(),
                    summary,
                },
            );
        }
        nice_log!("config_path set but unreadable: {config_path}, falling back");
    }

    // 2. sidecar next to the model file
    let sidecar = sidecar_config_path(converter_path);
    if let Some(cfg) = try_read_json(&sidecar) {
        let summary = summarize_config(&cfg);
        return (
            cfg,
            ConverterConfigInfo {
                source: "sidecar".into(),
                summary,
            },
        );
    }

    // 3. default
    let cfg = lightvc_core::ConverterConfig::default();
    let summary = summarize_config(&cfg);
    (
        cfg,
        ConverterConfigInfo {
            source: "default".into(),
            summary,
        },
    )
}

fn sidecar_config_path(converter_path: &str) -> String {
    // Strip the file extension and append `_config.json`.
    // `Path::with_extension("")` correctly handles dots inside directory names.
    let base = std::path::Path::new(converter_path).with_extension("");
    format!("{}_config.json", base.to_string_lossy())
}

fn summarize_config(cfg: &lightvc_core::ConverterConfig) -> String {
    format!(
        "{}, hidden={}, timbre={}",
        cfg.model_type, cfg.hidden_dim, cfg.enable_timbre
    )
}

fn load_pipeline(
    dac_path: &str,
    converter_path: &str,
    config_path: &str,
) -> anyhow::Result<(lightvc_core::pipeline::VcPipeline, ConverterConfigInfo)> {
    let device = candle_core::Device::Cpu;
    let dac_config = lightvc_core::DacConfig::default();

    let vb = lightvc_core::weights::load_varbuilder(
        std::path::Path::new(converter_path),
        candle_core::DType::F32,
        &device,
    )?;
    let (config, info) = load_converter_config(converter_path, config_path);
    nice_log!("Converter config [{}]: {}", info.source, info.summary);
    let converter = lightvc_core::converter::AnyConverter::new(config, vb)?;

    let pipeline = lightvc_core::pipeline::VcPipeline::new(
        std::path::Path::new(dac_path),
        &dac_config,
        converter,
        lightvc_core::converter::LatencyMode::Balanced,
        device,
    )?;
    Ok((pipeline, info))
}

// ---------------------------------------------------------------------------
// Pure-egui knob widget (no image assets needed)
// ---------------------------------------------------------------------------

/// Draw an interactive knob using egui primitives only.
///
/// - `value`: normalized 0.0..=1.0
/// - `label`: text below the knob
/// - `min`/`max`/`display`: for value formatting
/// Returns: new normalized value if dragged, or None
fn egui_knob(
    ui: &mut egui::Ui,
    _id_str: &str,
    value: f32,
    label: &str,
    display_text: &str,
) -> Option<f32> {
    let knob_size = 52.0;
    let (rect, response) = ui.allocate_exact_size(
        egui::vec2(knob_size + 20.0, knob_size + 30.0),
        egui::Sense::drag(),
    );

    let center = egui::pos2(rect.center().x, rect.min.y + knob_size / 2.0 + 4.0);
    let radius = knob_size / 2.0;

    let mut new_val = None;

    if response.dragged() {
        let drag = response.drag_delta().y;
        new_val = Some((value - drag * 0.005).clamp(0.0, 1.0));
    }
    if response.double_clicked() {
        new_val = Some(0.5);
    }

    let shown = new_val.unwrap_or(value);
    let painter = ui.painter();

    // Background circle
    painter.circle_filled(center, radius + 2.0, egui::Color32::from_rgb(28, 22, 38));

    // Arc background (270° span from -135° to +135°)
    let start_angle = -135.0_f32.to_radians();
    let end_angle = 135.0_f32.to_radians();
    let bg_points = (0..40)
        .map(|i| {
            let t = i as f32 / 39.0;
            let a = start_angle + (end_angle - start_angle) * t;
            center + egui::vec2(a.cos() * radius, a.sin() * radius)
        })
        .collect::<Vec<_>>();
    painter.add(egui::Shape::line(
        bg_points,
        egui::Stroke::new(3.0, egui::Color32::from_rgb(52, 40, 68)),
    ));

    // Value arc
    let val_end = start_angle + (end_angle - start_angle) * shown;
    let val_points = (0..40)
        .take(((shown * 39.0).round() as usize).max(1))
        .map(|i| {
            let t = i as f32 / 39.0;
            let a = start_angle + (val_end - start_angle) * t.min(1.0);
            center + egui::vec2(a.cos() * radius, a.sin() * radius)
        })
        .collect::<Vec<_>>();

    let arc_color = if response.dragged() {
        egui::Color32::from_rgb(255, 160, 210)
    } else if response.hovered() {
        egui::Color32::from_rgb(170, 140, 255)
    } else {
        egui::Color32::from_rgb(255, 130, 190)
    };
    if val_points.len() >= 2 {
        painter.add(egui::Shape::line(
            val_points,
            egui::Stroke::new(3.0, arc_color),
        ));
    }

    // Indicator line
    let ind_a = start_angle + (end_angle - start_angle) * shown;
    let ind_start = center + egui::vec2(ind_a.cos() * (radius - 8.0), ind_a.sin() * (radius - 8.0));
    let ind_end = center + egui::vec2(ind_a.cos() * radius, ind_a.sin() * radius);
    painter.line_segment([ind_start, ind_end], egui::Stroke::new(2.5, arc_color));

    // Inner circle
    painter.circle_filled(center, radius - 6.0, egui::Color32::from_rgb(42, 32, 56));

    // Glow when active
    if response.dragged() {
        painter.circle_stroke(
            center,
            radius + 4.0,
            egui::Stroke::new(
                2.0,
                egui::Color32::from_rgba_premultiplied(255, 130, 190, 60),
            ),
        );
    }

    // Value text in center
    painter.text(
        center,
        egui::Align2::CENTER_CENTER,
        display_text,
        egui::FontId::proportional(10.0),
        egui::Color32::from_rgb(240, 235, 250),
    );

    // Label below
    painter.text(
        egui::pos2(center.x, rect.min.y + knob_size + 12.0),
        egui::Align2::CENTER_TOP,
        label,
        egui::FontId::proportional(11.0),
        egui::Color32::from_rgb(160, 150, 180),
    );

    new_val
}

// ---------------------------------------------------------------------------
// CLAP export
// ---------------------------------------------------------------------------

impl ClapPlugin for LightVcPlugin {
    const CLAP_ID: &'static str = "com.lightvc.lightvc";
    const CLAP_DESCRIPTION: Option<&'static str> = Some("Real-time voice conversion");
    const CLAP_MANUAL_URL: Option<&'static str> = Some(Self::URL);
    const CLAP_SUPPORT_URL: Option<&'static str> = None;
    const CLAP_FEATURES: &'static [ClapFeature] = &[
        ClapFeature::AudioEffect,
        ClapFeature::Stereo,
        ClapFeature::Mono,
        ClapFeature::Utility,
    ];
}

nice_export_clap!(LightVcPlugin);

// ---------------------------------------------------------------------------
// VST3 wrapper export (via clap-wrapper, Steinberg VST3 SDK is MIT as of 2025)
// ---------------------------------------------------------------------------

#[cfg(feature = "vst3")]
clap_wrapper::export_vst3!();
